name: xpert_lab_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  velocity_x: ^4.1.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.3
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.8.4
  syncfusion_flutter_charts: ^22.1.39
  fl_chart: ^0.63.0
  file_picker: ^5.3.3
  cached_network_image: ^3.2.3
  dropdown_button2: ^2.3.7
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  
  uses-material-design: true

